version: '3.8'

services:
  backend:
    container_name: nest-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
      - ./backend/uploads:/home/uploads
    networks:
      - preservacao-network

  frontend:
    container_name: vite-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    networks:
      - preservacao-network
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:14
    container_name: preservacao-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preservacaoDigital
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - preservacao-network

volumes:
  db_data:

networks:
  preservacao-network:
    driver: bridge