version: '3.8'

services:
  backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"
    networks:
      - preservacao-network
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./uploads:/home/uploads

  db:
    image: postgres:14
    container_name: preservacao-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preservacaoDigital
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - preservacao-network

volumes:
  db_data:
  archivematica_pipeline_data:
  

networks:
  preservacao-network:
    driver: bridge
